// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PostMod from "./postMod.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function getPara(text) {
  return "<p class=\"post-text\">" + text + "</p>";
}

function getDescription(arr) {
  var postText = Belt_Array.map(arr, getPara);
  return postText.join("\n");
}

function createPost(x, index) {
  var i = String(index);
  return "<div id=\"block-" + i + "\" class=\"post\">\n      <h2 class=\"post-heading\">" + PostMod.Post.title(x) + "</h2>\n      <h3>" + PostMod.Post.author(x) + "</h3>\n      " + getDescription(PostMod.Post.text(x)) + "\n      <button id=\"block-delete-" + i + "\" class=\"button button-danger\">\n        Remove this post\n      </button>\n   </div>";
}

export {
  getPara ,
  getDescription ,
  createPost ,
  
}
/* No side effect */
