// Generated by ReScript, PLEASE EDIT WITH CARE


function deletePost(idVal, id) {
  if (id !== "None") {
    window.clearTimeout(id);
  }
  var blk = document.getElementById("block-" + idVal);
  document.body.removeChild(blk);
  var delBlk = document.getElementById("delete-block-" + idVal);
  return document.body.removeChild(delBlk);
}

export {
  deletePost ,
  
}
/* No side effect */
