// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "bs-platform/lib/es6/belt_Int.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

function make(title, author, text) {
  return {
          title: title,
          author: author,
          text: text
        };
}

function title(t) {
  return t.title;
}

function author(t) {
  return t.author;
}

function text(t) {
  return t.text;
}

var Post = {
  make: make,
  title: title,
  author: author,
  text: text
};

var posts = [
  {
    title: "The Razor's Edge",
    author: "W. Somerset Maugham",
    text: [
      "\"I couldn't go back now. I'm on the threshold. I see vast lands of the spirit stretching out before me,\n    beckoning, and I'm eager to travel them.\"",
      "\"What do you expect to find in them?\"",
      "\"The answers to my questions. I want to make up my mind whether God is or God is not. I want to find out why\n    evil exists. I want to know whether I have an immortal soul or whether when I die it's the end.\""
    ]
  },
  {
    title: "Ship of Destiny",
    author: "Robin Hobb",
    text: [
      "He suddenly recalled a callow boy telling his tutor that he dreaded the sea voyage home, because he would have\n        to be among common men rather than thoughtful acolytes like himself. What had he said to Berandol?",
      "\"Good enough men, but not like us.\"",
      "Then, he had despised the sort of life where simply getting from day to day prevented a man from ever taking\n        stock of himself. Berandol had hinted to him then that a time out in the world might change his image of folk\n        who labored every day for their bread. Had it? Or had it changed his image of acolytes who spent so much time in\n        self-examination that they never truly experienced life?"
    ]
  },
  {
    title: "A Guide for the Perplexed: Conversations with Paul Cronin",
    author: "Werner Herzog",
    text: ["Our culture today, especially television, infantilises us. The indignity of it kills our imagination. May I propose a Herzog dictum? Those who read own the world. Those who watch television lose it. Sitting at home on your own, in front of the screen, is a very different experience from being in the communal spaces of the world, those centres of collective dreaming. Television creates loneliness. This is why sitcoms have added laughter tracks which try to cheat you out of your solitude. Television is a reflection of the world in which we live, designed to appeal to the lowest common denominator. It kills spontaneous imagination and destroys our ability to entertain ourselves, painfully erasing our patience and sensitivity to significant detail."]
  }
];

function getIndexFromId(node) {
  var id = node.id;
  var id_len = id.length;
  return id.slice(id_len - 1 | 0);
}

function valueFromOption(value) {
  if (value !== undefined) {
    return value;
  } else {
    return -1;
  }
}

function deleteDiv(id) {
  var value = Belt_Int.fromString(id);
  var id_int = value !== undefined ? value : -1;
  if (id_int >= 0) {
    return "<div id=\"delete-block-" + id + "\" class=\"post-deleted pt-1\">\n      <p class=\"text-center\">\n        This post from <em>" + Caml_array.get(posts, id_int).title + " by " + Caml_array.get(posts, id_int).author + "</em> will be\n        permanently removed in 10 seconds.\n      </p>\n      <div class=\"flex-center\">\n        <button id=\"block-restore-" + id + "\" class=\"button button-warning mr-1\">\n          Restore\n        </button>\n        <button id=\"block-delete-immediate-" + id + "\" class=\"button button-danger\">\n          Delete Immediately\n        </button>\n      </div>\n      <div class=\"post-deleted-progress\"></div>\n    </div>";
  } else {
    return "<div></div>";
  }
}

function restorePost(e, id) {
  window.clearTimeout(id);
  var id_val = getIndexFromId(e.currentTarget);
  var blk = document.getElementById("block-" + id_val);
  blk.style.display = "block";
  var delBlk = document.getElementById("delete-block-" + id_val);
  return document.body.removeChild(delBlk);
}

function deletePost(e, id) {
  window.clearTimeout(id);
  var id_val = getIndexFromId(e.currentTarget);
  var blk = document.getElementById("block-" + id_val);
  document.body.removeChild(blk);
  var delBlk = document.getElementById("delete-block-" + id_val);
  return document.body.removeChild(delBlk);
}

function autoDelete(id_val) {
  var blk = document.getElementById("block-" + id_val);
  document.body.removeChild(blk);
  var delBlk = document.getElementById("delete-block-" + id_val);
  return document.body.removeChild(delBlk);
}

function removeChild(e) {
  var id_val = getIndexFromId(e.currentTarget);
  var blk = document.getElementById("block-" + id_val);
  blk.insertAdjacentHTML("afterend", deleteDiv(id_val));
  var restoreBlk = document.getElementById("block-restore-" + id_val);
  var delBlk = document.getElementById("block-delete-immediate-" + id_val);
  blk.style.display = "none";
  var timer_id = window.setTimeout((function (param) {
          return autoDelete(id_val);
        }), 10000);
  delBlk.addEventListener("click", (function (e) {
          return deletePost(e, timer_id);
        }));
  restoreBlk.addEventListener("click", (function (e) {
          return restorePost(e, timer_id);
        }));
  
}

function getPara(text) {
  return "<p class=\"post-text\">" + text + "</p>";
}

function getDescription(arr) {
  var postText = Belt_Array.map(arr, getPara);
  return postText.join("\n");
}

function createPost(x, index) {
  var i = String(index);
  return "<div id=\"block-" + i + "\" class=\"post\">\n      <h2 class=\"post-heading\">" + x.title + "</h2>\n      <h3>" + x.author + "</h3>\n      " + getDescription(x.text) + "\n      <button id=\"block-delete-" + i + "\" class=\"button button-danger\">\n        Remove this post\n      </button>\n   </div>";
}

function initialize(param) {
  console.log("Working");
  var values = Belt_Array.mapWithIndex(posts, (function (index, x) {
          return createPost(x, index);
        }));
  document.body.insertAdjacentHTML("beforeend", values);
  return Belt_Array.forEachWithIndex(posts, (function (i, param) {
                var i_str = String(i);
                var btn = document.getElementById("block-delete-" + i_str);
                return btn.addEventListener("click", removeChild);
              }));
}

export {
  Post ,
  posts ,
  getIndexFromId ,
  valueFromOption ,
  deleteDiv ,
  restorePost ,
  deletePost ,
  autoDelete ,
  removeChild ,
  getPara ,
  getDescription ,
  createPost ,
  initialize ,
  
}
/* No side effect */
