// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Delete from "./delete.bs.js";
import * as PostMod from "./postMod.bs.js";
import * as Restore from "./restore.bs.js";
import * as Belt_Int from "bs-platform/lib/es6/belt_Int.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

function deleteDiv(posts, id) {
  var postDiv = document.getElementById("block-" + id);
  var parentDiv = document.createElement("div");
  parentDiv.id = "delete-block-" + id;
  var x = Belt_Int.fromString(id);
  parentDiv.innerHTML = x !== undefined ? "<div class=\"post-deleted pt-1\">\n      <p class=\"text-center\">\n        This post from <em>" + PostMod.Post.title(Caml_array.get(posts, x)) + " by " + PostMod.Post.author(Caml_array.get(posts, x)) + "</em> will be\n        permanently removed in 10 seconds.\n      </p>\n      <div class=\"flex-center\">\n        <button id=\"block-restore-" + id + "\" class=\"button button-warning mr-1\">\n          Restore\n        </button>\n        <button id=\"block-delete-immediate-" + id + "\" class=\"button button-danger\">\n          Delete Immediately\n        </button>\n      </div>\n      <div class=\"post-deleted-progress\"></div>\n    </div>" : "";
  return document.body.insertBefore(parentDiv, postDiv);
}

function removeChild(posts, idVal) {
  var blk = document.getElementById("block-" + idVal);
  deleteDiv(posts, idVal);
  var restoreBlk = document.getElementById("block-restore-" + idVal);
  var delBlk = document.getElementById("block-delete-immediate-" + idVal);
  blk.style.display = "none";
  var timer_id = window.setTimeout((function (param) {
          return Delete.deletePost(idVal, "None");
        }), 10000);
  delBlk.addEventListener("click", (function (param) {
          return Delete.deletePost(idVal, timer_id);
        }));
  return restoreBlk.addEventListener("click", (function (param) {
                return Restore.restorePost(idVal, timer_id);
              }));
}

export {
  deleteDiv ,
  removeChild ,
  
}
/* No side effect */
