// Generated by ReScript, PLEASE EDIT WITH CARE


function restorePost(idVal, id) {
  window.clearTimeout(id);
  var blk = document.getElementById("block-" + idVal);
  blk.style.display = "block";
  var delBlk = document.getElementById("delete-block-" + idVal);
  return document.body.removeChild(delBlk);
}

export {
  restorePost ,
  
}
/* No side effect */
